CREATE OR REPLACE TABLE note (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    todo_id INT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NULL,
    content VARCHAR(1000)
);

ALTER TABLE note
    CHANGE modified_at
        modified_at TIMESTAMP NOT NULL
            DEFAULT CURRENT_TIMESTAMP
            ON UPDATE CURRENT_TIMESTAMP;
